services:
  backend:
    build: ./apps/backend
    container_name: kimo-labs-backend
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - CHROMA_HOST=chroma-server
      - CHROMA_PORT=8000
    ports:
      - "8001:8000"
    volumes:
      - ./data/docs:/app/docs
      - ./data/db:/app/db
      - ./hf_cache:/root/.cache/huggingface
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - chroma-server
    restart: unless-stopped

  chroma-server:
    image: chromadb/chroma:latest
    container_name: kimo-labs-chroma
    ports:
      - "8002:8000"
    volumes:
      - ./data/chroma:/chroma/chroma
    environment:
      - PERSIST_DIRECTORY=/chroma/chroma
      - IS_PERSISTENT=TRUE
    restart: unless-stopped

  frontend:
    build: ./apps/frontend
    container_name: kimo-labs-frontend
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://10.10.20.144:8001
    depends_on:
      - backend
    restart: unless-stopped

  chroma-admin:
    image: fengzhichao/chromadb-admin:latest
    container_name: kimo-labs-chroma-admin
    environment:
      - CHROMA_URL=http://chroma-server:8000
    ports:
      - "8003:3000"
    depends_on:
      - chroma-server
    restart: unless-stopped
